### PR TITLE
Update to 'Dart 3 compatible'

### LINKED ISSUE #50: Update to 'Dart 3 compatible'

### PR DESCRIPTION
**Pull request by hajajmaor**
Fixes #50

### CODE REVIEW

**Comment by leynier** [comment]
Hi @FilledStacks, can you please merge this PR? We need your help because the new Flutter release (3.10.1) is causing some issues with upgrading to Dart 3.0.1. Thank you in advance! 🙏🙇‍♂️

**Comment by hajajmaor** [comment]
> Hi @FilledStacks, can you please merge this PR? We need your help because the new Flutter release (3.10.1) is causing some issues with upgrading to Dart 3.0.1. Thank you in advance! 🙏🙇‍♂️

I have updated my master branch, use it like this until @FilledStacks merges this PR.

  responsive_builder:
    git:
      url: https://github.com/hajajmaor/responsive_builder/

**Comment by FilledStacks** [comment]
Merging in now. thanks for making the PR

**Review by FilledStacks — APPROVED** [review]
LGTM

**Comment by FilledStacks** [comment]
Jeez. This fix is broken. dart 4 doesn't exist. I will fix this now and push.

**Comment by FilledStacks** [comment]
Fixed

**Comment by hajajmaor** [comment]
In a new Flutter project, you can see that the env should be max  v4.0.0. So that's why I wrote version 4.

image

**Pull request merged**
