### PR TITLE
Adding the ability to create widgets on demand

### PR DESCRIPTION
**Pull request by mareklat**

### CODE REVIEW

**Comment by FilledStacks** [comment]
Hi @mareklat could you add an example to the readme of how this would be used and why. I don't quite see the point of the change.

**Comment by mareklat** [comment]
@FilledStacks Of course. I just updated the readme.

**Comment by FilledStacks** [comment]
That makes perfect sense now. awesome man, thanks a lot. didn't even know i wanted that 😁 I'll  merge and push as soon as I'm at my PC.

**Comment by FilledStacks** [comment]
@mareklat It has been published. Sorry for the delay. 

Thanks again for the update. I appreciate it.

**Pull request merged**
